base: http://files.travis-ci.org/boxes/bases/precise32_base_v2.box
json:
  rabbitmq:
    service:
      enabled: true
  elasticsearch:
    service:
      enabled: true
  redis:
    service:
      enabled: true
  riak:
    service:
      enabled: true
  cassandra:
    service:
      enabled: true
  mongodb:
    service:
      enabled: true
  rvm:
    default: 1.9.3-p327
    rubies:
      - name: 1.9.3-p327
    gems:
      - bundler
      - rake
      - chef
  mysql:
    server_root_password: ""
  postgresql:
    max_connections: 256
  travis_build_environment:
    use_tmpfs_for_builds: false
recipes:
  #
  # Travis environment + build toolchain
  #
  - travis_build_environment
  - apt
  - build-essential
  - clang::tarball
  - golang::multi
  - networking_basic
  - openssl
  - sysctl
  - git::ppa
  - mercurial
  - bazaar
  - subversion
  - scons
  - unarchivers
  #
  # additional libraries needed to run headless WebKit,
  # build parsers, for ossp-uuid to work and so on
  #
  - libqt4
  - libgdbm
  - libncurses
  - libossp-uuid
  - libffi
  - ragel
  - imagemagick
  - mingw32
  #
  # JDK and related build toolchain
  #
  - java
  - ant
  - maven3
  - leiningen
  - sbt
  - gradle::tarball
  #
  # Ruby via RVM (default Debian installations are secure at the cost of
  # being unusable without PATH tweaking, for our VMs we can just go with RVM.
  # This includes rubygems, bundler and rake.
  #
  - rvm
  - rvm::multi
  #
  # Python and pip
  #
  - python
  - python::pip
  #
  # Node.js
  #
  - nodejs::multi
  #
  # Data stores
  #
  - sqlite
  - postgresql::client
  - mysql::client
  - mysql::server_on_ramfs
  - postgresql::server_on_ramfs
  - redis::ppa
  - riak
  - mongodb
  - couchdb::ppa
  - memcached
  - neo4j-server::tarball
  - cassandra::tarball
  #
  # Messaging
  #
  - rabbitmq::with_management_plugin
  - zeromq::ppa
  #
  # Search
  #
  - elasticsearch
  - sphinx::all
  #
  # Headless WebKit, browsers, Selenium toolchain, etc
  #
  - xserver
  - firefox
  - chromium
  - phantomjs::tarball
  #
  # Debugging & support
  #
  - emacs::nox
  - vim
  - sweeper